apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2018-08-19T23:54:16Z
  generation: 1
  labels:
    run: example
  name: example
  namespace: default
  resourceVersion: "49623"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/example
  uid: 2e4b61d9-a40b-11e8-a12b-080027b15a4b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: example
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: example
    spec:
      containers:
      - image: nginx:1.13.5-alpine
        imagePullPolicy: IfNotPresent
        name: example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
