apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-19T23:54:27Z
  labels:
    run: KeplerVMSNginx
  name: KeplerVMSNginx
  namespace: default
  resourceVersion: "49659"
  selfLink: /api/v1/namespaces/default/services/KeplerVMSNginx
  uid: 34ea739c-a40b-11e8-a12b-080027b15a4b
spec:
  clusterIP: 10.108.201.144
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31342
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: KeplerVMSNginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
