piVersion: v1
kind: Service
metadata:
  labels:
    run: kepler-vms-nginx
  name: kepler-vms-nginx
  namespace: default
spec:
  clusterIP: 10.108.201.144
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30453
    name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    type: NodePort
  - nodePort: 31935
    name: rtmp
    port: 1935
    protocol: TCP
    targetPort: 1935
    type: NodePort
  selector:
    run: kepler-vms-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

