kind: PersistentVolume
apiVersion: v1
metadata:
  name: vms-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/vms/data"
