# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kepler/nginx
  tag: 0.1
  pullPolicy: Never

initimage:
  repository: busybox
  tag: lastest
  pullPolicy: Never

service:
  name: kepler-vms-nginx
  type: NodePort
  externalPort: 8080
  internalPort: 8080
  selector:
    run: kepler-vms-nginx
ingress:
  enabled: false
  path: /
  hosts:
    - media-server.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
